### ISSUE TITLE
Add dependencies to classpath

### ISSUE THREAD

**Issue by randombyte-developer** [ImMorpheus/SpongeStart#5]
Dependencies defined in the build.gradle don't get added to the classpath. This is crucial to run all of my plugins(using the Koltin runtime and stdlib).

**Comment by randombyte-developer** [comment]
https://github.com/randombyte-developer/command-utils is a smaller plugin, this might be easier to test. Thanks for your effort. If you have problems running my plugin reach out to me!

**Comment by ImMorpheus** [comment]
I think I'm getting something wrong. 

I generated a run config for command-utils.

```
dependencies {
    shadow "org.jetbrains.kotlin:kotlin-stdlib-jre8:1.1.2-5"
    kapt "org.spongepowered:spongeapi:5.1.0"
    shadow("com.github.randombyte-developer.kosp:kosp:v0.5.1") { transitive = false }
}
```

So I have to include all the paths to the dependencies in jar form:

`-classpath $PROJECT_DIR$/run/vanilla/server.jar:$USER_HOME$/.gradle/caches/modules-2/files-2.1/com.github.randombyte-developer.kosp/kosp/v0.5.1/1ac125998fd0c3953724ce3400286cc1fa4e3118/kosp-v0.5.1.jar:$USER_HOME$/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre8/1.1.2-5/270420dbf234b53aa3f044011825b6876385e7a0/kotlin-stdlib-jre8-1.1.2-5.jar:$PROJECT_DIR$/build/classes/main`

However IntelliJ doesn't like it:

```
[20:41:41 ERROR] [Sponge]: Failed to load plugin: CommandUtils 1.5 (from unknown)
java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at de.randombyte.kosp.bstats.BStats.<clinit>(BStats.kt) ~[BStats.class:?]
	at de.randombyte.kosp.bstats.BStats$$FastClassByGuice$$2e261077.newInstance(<generated>) ~[server.jar:?]
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[server.jar:1.10.2-5.2.0-BETA-396]
	at org.spongepowered.server.plugin.VanillaPluginContainer.<init>(VanillaPluginContainer.java:77) ~[VanillaPluginContainer.class:1.10.2-5.2.0-BETA-396]
	at org.spongepowered.server.plugin.VanillaPluginManager.loadPlugin(VanillaPluginManager.java:138) ~[VanillaPluginManager.class:1.10.2-5.2.0-BETA-396]
	at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_141]
	at org.spongepowered.server.plugin.VanillaPluginManager.loadPlugins(VanillaPluginManager.java:70) [VanillaPluginManager.class:1.10.2-5.2.0-BETA-396]
	at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:176) [SpongeVanilla.class:1.10.2-5.2.0-BETA-396]
	at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$zoc000(SourceFile:1224) [ld.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:112) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:428) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
	... 30 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
	... 30 more
```

PS: I also tried to change spongeapi to 5.2.0-SNAPSHOT (with no luck).

**Comment by randombyte-developer** [comment]
The stdlib compile/shadow statement is a transitive decency, it also contains the Kotlin runtime(which is missing here in the classpath).
To see the classpath generated by IntelliJ create a new run config which is completly empty(also no main class specified) but only the module is set to main. Then run the configuration regardless of any errors. The terminal in IntelliJ opens. Checkout the command the IDE executed. There is a long part for the classpath option. There should be the Kotlin runtime. 

In the end the goal is to find the method how IntelliJ generates this command and append it with the server jar.

**Comment by ImMorpheus** [comment]
> In the end the goal is to find the method how IntelliJ generates this command and append it with the server jar.

Done. Hopefully I will be able to release something tonight.

**Comment by ImMorpheus** [comment]
Try
`id 'com.qixalite.spongestart2' version 'dev98'`

Note:
I haven't tested SpongeForge
You need Gradle 4.0+
You need to build the plugin at least once before using SpongeStart

Let me know how it goes, I want to do some cleanup before releasing the new version.

**Comment by randombyte-developer** [comment]
That works great!

For issue #6: After some investigation the build path must be `build/classes/java/main`, otherwise the child folders get interpreted as java packages and the ClassLoader can't find any classes of the plugin.

Tested with SpongeForge: `java.lang.NoSuchMethodError: ninja.leaping.configurate.hocon.HoconConfigurationLoader$Builder.setRenderOptions(Lconfigurate/typesafe/config/ConfigRenderOptions;)Lninja/leaping/configurate/hocon/HoconConfigurationLoader$Builder;`, I think there is some version conflict with Configurate.

**Comment by ImMorpheus** [comment]
> For issue 6: After some investigation the build path must be build/classes/java/main, otherwise the child folders get interpreted as java packages and the ClassLoader can't find any classes of the plugin.

Yeah, I thought so. That version should retrieve the build dir dynamically (although the current system is broken for java plugins). In the next version you could technically set the build dir to something outside the project dir.

> Tested with SpongeForge: java.lang.NoSuchMethodError: ninja.leaping.configurate.hocon.HoconConfigurationLoader$Builder.setRenderOptions(Lconfigurate/typesafe/config/ConfigRenderOptions;)Lninja/leaping/configurate/hocon/HoconConfigurationLoader$Builder;, I think there is some version conflict with Configurate.

I have no idea what is happening here. Judging from _gradle dependencies_ there's only one version of Configurate.
Out of curiosity, were you able to run a forge server with the old version of SpongeStart ?

**Comment by randombyte-developer** [comment]
I don't if it worked before because I didn't need forge back then. I'll try soon.
